import { AnalysisResult } from "./types";

export const DEMO_DATA: AnalysisResult = {
  id: "demo-001",
  industry: "新能源汽车",
  createdAt: new Date().toISOString(),
  dimensions: [
    {
      name: "实体层",
      icon: "🏢",
      color: "#FF6B6B",
      cssClass: "dim-entity",
      keywords: [
        { word: "比亚迪", definition: "中国最大新能源汽车制造商，涵盖纯电和插混车型", related: ["特斯拉", "宁德时代", "弗迪电池"] },
        { word: "特斯拉", definition: "全球电动车标杆，Model 3/Y为主力车型", related: ["比亚迪", "蔚来", "纯电动车"] },
        { word: "蔚来", definition: "高端智能电动车品牌，以换电模式著称", related: ["小鹏", "理想", "换电"] },
        { word: "小鹏汽车", definition: "主打智能化辅助驾驶的造车新势力", related: ["蔚来", "理想", "NGP"] },
        { word: "理想汽车", definition: "增程式电动车代表，家庭奶爸车定位", related: ["蔚来", "小鹏", "增程式"] },
        { word: "华为", definition: "智能汽车解决方案供应商，HI模式和智选模式", related: ["小康股份", "极狐", "鸿蒙座舱"] },
        { word: "宁德时代", definition: "全球最大动力电池供应商，主打三元锂和磷酸铁锂", related: ["比亚迪", "弗迪电池", "动力电池"] },
        { word: "埃安", definition: "广汽旗下新能源品牌，Hyper GT为主力", related: ["比亚迪", "吉利", "纯电动车"] },
        { word: "大众安徽", definition: "大众在华第三家合资公司，专攻新能源", related: ["大众ID系列", "MEB平台", "纯电动车"] },
        { word: "小米汽车", definition: "2024年入市，SU7车型主打生态和智能", related: ["华为", "理想", "智能座舱"] },
      ],
    },
    {
      name: "术语层",
      icon: "📖",
      color: "#4ECDC4",
      cssClass: "dim-term",
      keywords: [
        { word: "动力电池", definition: "新能源汽车核心储能部件，主要分三元锂和磷酸铁锂", related: ["宁德时代", "弗迪电池", "固态电池"] },
        { word: "800V平台", definition: "高压快充架构，充电速度大幅提升", related: ["SiC碳化硅", "高压快充", "充电桩"] },
        { word: "SiC碳化硅", definition: "第三代半导体材料，用于电控系统效率提升", related: ["800V平台", "电控", "功率半导体"] },
        { word: "固态电池", definition: "下一代电池技术，能量密度高、安全性好", related: ["动力电池", "宁德时代", "赣锋锂业"] },
        { word: "CTC技术", definition: "电池底盘一体化，减少零部件数量", related: ["动力电池", "比亚迪", "整车平台"] },
        { word: "电控", definition: "电动汽车电机控制系统，核心部件", related: ["SiC碳化硅", "IGBT", "功率半导体"] },
        { word: "IGBT", definition: "功率半导体器件，用于电控系统", related: ["电控", "SiC碳化硅", "比亚迪"] },
        { word: "纯电动车", definition: "BEV，完全靠动力电池驱动", related: ["特斯拉", "比亚迪", "续航里程"] },
        { word: "插电混动", definition: "PHEV，可外接充电的混合动力车", related: ["增程式", "比亚迪DM-i", "纯电续航"] },
        { word: "增程式", definition: "REEV，发动机只发电不直接驱动车轮", related: ["理想汽车", "插电混动", "问界"] },
      ],
    },
    {
      name: "政策层",
      icon: "📜",
      color: "#45B7D1",
      cssClass: "dim-policy",
      keywords: [
        { word: "双积分政策", definition: "企业平均燃料消耗量+新能源汽车积分并行管理", related: ["碳中和", "新能源补贴", "车企合规"] },
        { word: "碳中和", definition: "2030碳达峰、2060碳中和目标", related: ["双积分政策", "绿电", "新能源汽车"] },
        { word: "新能源补贴", definition: "国家对新能源汽车购买给予的财政补贴（已逐步退坡）", related: ["双积分政策", "购置税减免", "绿牌"] },
        { word: "购置税减免", definition: "新能源汽车免征车辆购置税优惠政策", related: ["新能源补贴", "绿牌", "购车优惠"] },
        { word: "绿牌", definition: "新能源汽车专用号牌，享受路权优待", related: ["购置税减免", "不限行", "充电优惠"] },
        { word: "充电桩建设", definition: "国家推动公共充电基础设施建设规划", related: ["800V平台", "公共充电", "私桩"] },
        { word: "新能源汽车发展规划", definition: "国务院发布的新能源汽车产业发展中长期规划", related: ["碳中和", "双积分政策", "动力电池"] },
        { word: "动力电池回收", definition: "新能源汽车废旧电池回收利用管理体系", related: ["宁德时代", "格林美", "退役电池"] },
        { word: "碳足迹核算", definition: "汽车全生命周期碳排放计量要求", related: ["碳中和", "动力电池", "绿电"] },
        { word: "自动驾驶法规", definition: "L2/L3级自动驾驶上路准入和责任界定规则", related: ["智能驾驶", "L3", "高精地图"] },
      ],
    },
    {
      name: "资本层",
      icon: "💰",
      color: "#96CEB4",
      cssClass: "dim-capital",
      keywords: [
        { word: "宁德时代定增", definition: "宁德时代2022年巨额定增融资扩产", related: ["宁德时代", "动力电池", "产业链投资"] },
        { word: "比亚迪半导体", definition: "比亚迪分拆IGBT等半导体业务独立融资", related: ["比亚迪", "IGBT", "IPO"] },
        { word: "蔚来美元融资", definition: "蔚来多次美元融资支撑研发和运营", related: ["蔚来", "造车新势力", "融资"] },
        { word: "小米汽车投资", definition: "小米首期100亿人民币投资汽车业务", related: ["小米汽车", "雷军", "智能汽车"] },
        { word: "华为车BU", definition: "华为智能汽车解决方案业务部独立运营", related: ["华为", "HI模式", "鸿蒙座舱"] },
        { word: "赣锋锂业", definition: "锂矿资源和动力电池回收布局", related: ["固态电池", "锂矿", "动力电池回收"] },
        { word: "弗迪电池", definition: "比亚迪旗下电池业务，独立供货其他车企", related: ["比亚迪", "动力电池", "刀片电池"] },
        { word: "理想IPO", definition: "理想汽车美股和港股双重上市", related: ["理想汽车", "造车新势力", "融资"] },
        { word: "广汽埃安融资", definition: "埃安完成混改和独立融资", related: ["埃安", "广汽", "混改"] },
        { word: "地平线机器人", definition: "自动驾驶芯片独角兽，获得多家车企投资", related: ["自动驾驶芯片", "华为", "大众"] },
      ],
    },
    {
      name: "趋势层",
      icon: "📈",
      color: "#FFEAA7",
      cssClass: "dim-trend",
      keywords: [
        { word: "价格战", definition: "2023年起特斯拉带头降价引发行业价格竞争", related: ["特斯拉", "比亚迪", "市场竞争"] },
        { word: "800V快充", definition: "2023年开始普及高压快充平台", related: ["800V平台", "SiC碳化硅", "充电桩"] },
        { word: "城市NOA", definition: "城市道路自动辅助驾驶快速推进", related: ["智能驾驶", "小鹏", "华为"] },
        { word: "出海加速", definition: "中国新能源车出口量快速增长", related: ["比亚迪", "特斯拉", "欧洲市场"] },
        { word: "磷酸铁锂回潮", definition: "低成本磷酸铁锂装机量超越三元锂", related: ["宁德时代", "比亚迪", "动力电池"] },
        { word: "氢能路线", definition: "氢燃料电池汽车作为商用车方向之一", related: ["丰田", "氢燃料电池", "商用车"] },
        { word: "电池底盘一体化", definition: "CTC/CTB技术减少零部件和重量", related: ["CTC技术", "比亚迪", "零跑"] },
        { word: "增程式回暖", definition: "增程式因成本和里程优势重获市场关注", related: ["增程式", "理想", "问界"] },
        { word: "MPV电动化", definition: "纯电和混动MPV成为新蓝海", related: ["腾势D9", "极氪009", "岚图梦想家"] },
        { word: "造车资质收紧", definition: "国家收紧新能源车生产资质审批", related: ["政策层", "代工模式", "自建产能"] },
      ],
    },
    {
      name: "产业链层",
      icon: "🔗",
      color: "#DDA0DD",
      cssClass: "dim-chain",
      keywords: [
        { word: "锂矿", definition: "动力电池核心原材料，南美和澳大利亚为主", related: ["赣锋锂业", "天齐锂业", "动力电池"] },
        { word: "钴矿", definition: "三元锂电池关键材料，刚果金主导", related: ["洛阳钼业", "三元锂", "动力电池"] },
        { word: "正极材料", definition: "磷酸铁锂或三元材料，电池成本占比最高", related: ["德方纳米", "动力电池", "磷酸铁锂"] },
        { word: "负极材料", definition: "人造石墨为主，电池核心材料之一", related: ["贝特瑞", "动力电池", "硅碳负极"] },
        { word: "隔膜", definition: "电池内部隔离正负极的材料", related: ["恩捷股份", "星源材质", "动力电池"] },
        { word: "电解液", definition: "电池内部离子传导介质", related: ["天赐材料", "新宙邦", "动力电池"] },
        { word: "电芯", definition: "动力电池最小PACK单元", related: ["宁德时代", "弗迪电池", "PACK"] },
        { word: "PACK", definition: "电池模组封装环节", related: ["电芯", "宁德时代", "整车"] },
        { word: "整车制造", definition: "汽车总装环节", related: ["比亚迪", "特斯拉", "整车"] },
        { word: "充电桩", definition: "新能源汽车补能基础设施", related: ["800V平台", "公共充电", "私桩"] },
      ],
    },
    {
      name: "对比层",
      icon: "⚖️",
      color: "#98D8C8",
      cssClass: "dim-compare",
      keywords: [
        { word: "纯电vs混动", definition: "BEV和PHEV/REEV两条技术路线之争", related: ["纯电动车", "插电混动", "增程式"] },
        { word: "特斯拉vs比亚迪", definition: "全球两大新能源巨头的全方位竞争", related: ["特斯拉", "比亚迪", "价格战"] },
        { word: "新势力vs传统车企", definition: "造车新势力智能化强，传统车企制造底蕴深", related: ["蔚来", "大众", "比亚迪"] },
        { word: "三元锂vs磷酸铁锂", definition: "两种动力电池技术路线的优劣势对比", related: ["动力电池", "宁德时代", "比亚迪"] },
        { word: "纯电平台vs油改电", definition: "专属纯电平台vs燃油车改造平台", related: ["MEB平台", "比亚迪e平台3.0", "纯电动车"] },
        { word: "换电vs快充", definition: "蔚来换电模式vs主流快充模式", related: ["蔚来", "800V平台", "充电桩"] },
        { word: "直营vs经销商", definition: "特斯拉新势力直营vs传统4S店模式", related: ["特斯拉", "蔚来", "传统车企"] },
        { word: "智驾方案对比", definition: "华为、小鹏、特斯拉FSD的方案差异", related: ["华为", "小鹏", "特斯拉"] },
        { word: "功率半导体对比", definition: "SiC碳化硅vs传统IGBT的效率差异", related: ["SiC碳化硅", "IGBT", "800V平台"] },
        { word: "成本控制能力", definition: "比亚迪垂直整合模式vs特斯拉规模化模式", related: ["比亚迪", "特斯拉", "价格战"] },
      ],
    },
  ],
  graph: {
    nodes: [
      // Sample nodes across dimensions
      { id: "比亚迪", dimension: "实体层", word: "比亚迪", definition: "中国最大新能源汽车制造商", related: ["特斯拉", "宁德时代"] },
      { id: "特斯拉", dimension: "实体层", word: "特斯拉", definition: "全球电动车标杆", related: ["比亚迪", "蔚来"] },
      { id: "宁德时代", dimension: "实体层", word: "宁德时代", definition: "全球最大动力电池供应商", related: ["比亚迪", "弗迪电池"] },
      { id: "蔚来", dimension: "实体层", word: "蔚来", definition: "高端智能电动车品牌", related: ["小鹏", "理想"] },
      { id: "小鹏汽车", dimension: "实体层", word: "小鹏汽车", definition: "主打智能化辅助驾驶", related: ["蔚来", "理想"] },
      { id: "理想汽车", dimension: "实体层", word: "理想汽车", definition: "增程式电动车代表", related: ["蔚来", "小鹏"] },
      { id: "华为", dimension: "实体层", word: "华为", definition: "智能汽车解决方案供应商", related: ["小米汽车", "小康股份"] },
      { id: "动力电池", dimension: "术语层", word: "动力电池", definition: "新能源汽车核心储能部件", related: ["宁德时代", "固态电池"] },
      { id: "800V平台", dimension: "术语层", word: "800V平台", definition: "高压快充架构", related: ["SiC碳化硅", "充电桩"] },
      { id: "SiC碳化硅", dimension: "术语层", word: "SiC碳化硅", definition: "第三代半导体材料", related: ["800V平台", "电控"] },
      { id: "固态电池", dimension: "术语层", word: "固态电池", definition: "下一代电池技术", related: ["动力电池", "宁德时代"] },
      { id: "纯电动车", dimension: "术语层", word: "纯电动车", definition: "完全靠动力电池驱动", related: ["特斯拉", "比亚迪"] },
      { id: "插电混动", dimension: "术语层", word: "插电混动", definition: "可外接充电的混合动力车", related: ["增程式", "比亚迪DM-i"] },
      { id: "增程式", dimension: "术语层", word: "增程式", definition: "发动机只发电不直接驱动", related: ["理想汽车", "插电混动"] },
      { id: "双积分政策", dimension: "政策层", word: "双积分政策", definition: "积分并行管理机制", related: ["碳中和", "新能源补贴"] },
      { id: "碳中和", dimension: "政策层", word: "碳中和", definition: "2030碳达峰2060碳中和", related: ["双积分政策", "绿电"] },
      { id: "新能源补贴", dimension: "政策层", word: "新能源补贴", definition: "国家财政补贴（逐步退坡）", related: ["双积分政策", "购置税减免"] },
      { id: "宁德时代定增", dimension: "资本层", word: "宁德时代定增", definition: "巨额定增融资扩产", related: ["宁德时代", "动力电池"] },
      { id: "弗迪电池", dimension: "资本层", word: "弗迪电池", definition: "比亚迪旗下电池业务", related: ["比亚迪", "动力电池"] },
      { id: "价格战", dimension: "趋势层", word: "价格战", definition: "特斯拉带头降价引发竞争", related: ["特斯拉", "比亚迪"] },
      { id: "城市NOA", dimension: "趋势层", word: "城市NOA", definition: "城市道路自动辅助驾驶", related: ["小鹏", "华为"] },
      { id: "出海加速", dimension: "趋势层", word: "出海加速", definition: "中国新能源车出口增长", related: ["比亚迪", "特斯拉"] },
      { id: "锂矿", dimension: "产业链层", word: "锂矿", definition: "动力电池核心原材料", related: ["赣锋锂业", "动力电池"] },
      { id: "正极材料", dimension: "产业链层", word: "正极材料", definition: "电池成本占比最高", related: ["德方纳米", "动力电池"] },
      { id: "电芯", dimension: "产业链层", word: "电芯", definition: "动力电池最小PACK单元", related: ["宁德时代", "PACK"] },
      { id: "充电桩", dimension: "产业链层", word: "充电桩", definition: "新能源汽车补能基础设施", related: ["800V平台", "公共充电"] },
      { id: "纯电vs混动", dimension: "对比层", word: "纯电vs混动", definition: "两条技术路线之争", related: ["纯电动车", "插电混动"] },
      { id: "三元锂vs磷酸铁锂", dimension: "对比层", word: "三元锂vs磷酸铁锂", definition: "两种技术路线对比", related: ["动力电池", "宁德时代"] },
      { id: "换电vs快充", dimension: "对比层", word: "换电vs快充", definition: "两种补能模式之争", related: ["蔚来", "800V平台"] },
    ],
    links: [
      { source: "比亚迪", target: "特斯拉", relation: "竞争" },
      { source: "比亚迪", target: "宁德时代", relation: "采购" },
      { source: "比亚迪", target: "弗迪电池", relation: "自供" },
      { source: "特斯拉", target: "宁德时代", relation: "采购" },
      { source: "蔚来", target: "小鹏", relation: "竞争" },
      { source: "蔚来", target: "理想", relation: "竞争" },
      { source: "理想", target: "增程式", relation: "应用" },
      { source: "华为", target: "小米汽车", relation: "竞争" },
      { source: "动力电池", target: "宁德时代", relation: "制造" },
      { source: "动力电池", target: "固态电池", relation: "升级" },
      { source: "800V平台", target: "SiC碳化硅", relation: "采用" },
      { source: "800V平台", target: "充电桩", relation: "配套" },
      { source: "纯电动车", target: "动力电池", relation: "搭载" },
      { source: "插电混动", target: "增程式", relation: "替代" },
      { source: "双积分政策", target: "碳中和", relation: "推动" },
      { source: "双积分政策", target: "新能源补贴", relation: "替代" },
      { source: "宁德时代定增", target: "宁德时代", relation: "融资" },
      { source: "弗迪电池", target: "比亚迪", relation: "隶属" },
      { source: "价格战", target: "特斯拉", relation: "发起" },
      { source: "价格战", target: "比亚迪", relation: "跟进" },
      { source: "城市NOA", target: "小鹏", relation: "研发" },
      { source: "城市NOA", target: "华为", relation: "研发" },
      { source: "出海加速", target: "比亚迪", relation: "主体" },
      { source: "锂矿", target: "动力电池", relation: "原料" },
      { source: "正极材料", target: "动力电池", relation: "材料" },
      { source: "电芯", target: "PACK", relation: "组成" },
      { source: "充电桩", target: "800V平台", relation: "配套" },
      { source: "纯电vs混动", target: "纯电动车", relation: "对比" },
      { source: "三元锂vs磷酸铁锂", target: "动力电池", relation: "技术" },
      { source: "换电vs快充", target: "蔚来", relation: "模式" },
    ],
  },
};
